name: cheapg
channels:
  - conda-forge
dependencies:
  - python
  # - pip
  # - conda-forge::folly
  # - conda-forge::tbb
  # - conda-forge/label/gcc7::gcc_linux-64
  # - conda-forge::pybind11
  - nvidia/label/cuda-12.1.1::cuda
  - nvidia/label/cuda-12.1.1::cuda-toolkit
  - nvidia/label/cuda-12.1.1::cuda-libraries
  - nvidia/label/cuda-12.1.1::cuda-cudart-dev
  # - mkl 
  # - mkl-include